logistic_regression:
  auc: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    XbFN7Dgw5T8=
  auc_ci: !!python/tuple
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      0ldNo4PN5D8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ktwaUo2Q5T8=
  best_params:
    classifier__C: 0.1
  model: LogisticRegression
  sensitivity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    8of2K8Ye4T8=
  specificity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    s8e3VUtZ5j8=
neural_network:
  auc: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    hlPv5VbR4j8=
  auc_ci: !!python/tuple
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      8vk6r5Bo4j8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      Exykb4A34z8=
  best_params:
    activation: tanh
    alpha: 0.0001
    hidden_layer_sizes: !!python/tuple
    - 100
    learning_rate_init: 0.001
  model: MLPClassifier
  sensitivity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    efKH9ivGzj8=
  specificity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    uFVLWe7K6z8=
xgboost:
  auc: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    bed+HBs/5T8=
  auc_ci: !!python/tuple
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      2ojBPXPh5D8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      21kiA9ie5T8=
  best_params:
    classifier__learning_rate: 0.1
    classifier__max_depth: 3
    classifier__n_estimators: 200
  model: XGBoost
  sensitivity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    CfPsdj/T4j8=
  specificity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    F7S1i8/r5D8=
