logistic_regression:
  auc: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    XbFN7Dgw5T8=
  auc_ci: !!python/tuple
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      0ldNo4PN5D8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ktwaUo2Q5T8=
  best_params:
    classifier__C: 0.1
  model: LogisticRegression
  sensitivity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    8of2K8Ye4T8=
  specificity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    s8e3VUtZ5j8=
neural_network:
  auc: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    sGoqVFoS5T8=
  auc_ci: !!python/tuple
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      PwkIEkW25D8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      7+gzwXl15T8=
  best_params:
    activation: relu
    alpha: 0.0001
    hidden_layer_sizes: !!python/tuple
    - 50
    - 30
    learning_rate_init: 0.01
  model: MLPClassifier
  sensitivity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    K91qNLGkZT8=
  specificity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    kxIdDMX87z8=
xgboost:
  auc: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    wcqZV6NI5T8=
  auc_ci: !!python/tuple
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      mRVgpUjq5D8=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ncrcBeen5T8=
  best_params:
    classifier__learning_rate: 0.1
    classifier__max_depth: 3
    classifier__n_estimators: 200
  model: XGBoost
  sensitivity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    pA1ZVj4Jgj8=
  specificity: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Nn4uR8X27z8=
